name: sst_rise
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dask
  - numpy
  - coiled
  - cf_xarray
  - fsspec
  - matplotlib
  - nc-time-axis
  - zarr
  - xarray-datatree
  - xarrayutils